nimbella/nimbella-cli

src/commands/key-value/clean.ts
src/commands/key-value/del.ts
src/commands/key-value/expire.ts
src/commands/key-value/get.ts
src/commands/key-value/getMany.ts
src/commands/key-value/list.ts
src/commands/key-value/llen.ts
src/commands/key-value/lrange.ts
src/commands/key-value/rpush.ts
src/commands/key-value/set.ts
src/commands/key-value/setMany.ts
src/commands/key-value/ttl.ts

Fixes https://github.com/nimbella-corp/nimbella-cli/issues/291

[key-value] Display errors returned by the actions

---

src/commands/key-value/list.ts
src/commands/object/list.ts
src/commands/web/list.ts
src/storage/clients.ts
src/storage/key-value.ts

Change `namespace` arg from positional param to optional in `web`, `object`, and `kv` `list` commands

[web|object|kv:list] commands - change namespace arg to flag

---

.eslintrc
deployer/src/NimBaseCommand.ts
deployer/src/api.ts
deployer/src/credentials.ts
deployer/src/deploy-struct.ts
deployer/src/deploy-to-bucket.ts
deployer/src/deploy.ts
deployer/src/file-reader.ts
deployer/src/finder-builder.ts
deployer/src/github-reader.ts
deployer/src/github.ts
deployer/src/includer.ts
deployer/src/index.ts
deployer/src/login.ts
deployer/src/project-reader.ts
deployer/src/util.ts
deployer/src/web-local.ts
package.json
src/commands/doc.ts
src/commands/info.ts
src/deployer/index.ts
src/generator/project.ts
src/generator/samples.ts
src/hooks/prerun.ts
src/storage/clients.ts
src/storage/key-value.ts
src/storage/util.ts

This PR lint rules and adjusts the code to conform to them.   The intent is to enforce these rules going forward.   Initially, enforcement will be manual (`npm run lint` or configure your IDE to do the equivalent).

Add lint rules, make code conform

---

commandAuthoringGuide.md
deployer/package.json
deployer/src/NimBaseCommand.ts
deployer/src/api.ts
deployer/src/deploy-struct.ts
deployer/src/deploy-to-bucket.ts
deployer/src/deploy.ts
deployer/src/finder-builder.ts
deployer/src/index.ts
deployer/src/project-reader.ts
deployer/src/slice-reader.ts
deployer/src/util.ts
package.json
src/commands/project/deploy.ts
src/commands/project/watch.ts
src/deployer/index.ts

This is being merged now so as to be available (hidden, undocumented) in the next stable release.   It needs to be there while the backend support is completed.

Support for remote build (remains hidden initially while backend support is completed)

---

src/commands/project/create.ts
src/commands/project/update.ts
src/generator/project.ts

Update [project:create|update] command to include

Update [project:create|update] command

---

src/commands/key-value/del.ts

Add an alias (kv:delete) for kv:del command

Add alias for kv:del command

---

src/commands/key-value/get.ts

[kv:get] pretty print JSON value if stored value is in JSON format

[kv:get] pretty print JSON

---

src/commands/project/create.ts
src/generator/project.ts
src/generator/samples.ts

This is not the best way to cater to the change request and might require a touch-up after #18 is merged. Additionally, this change also needs to be propagated to the plugins repo.

[project:create|update] add language aliases

---

src/commands/key-value/list.ts
src/commands/object/get.ts
src/commands/object/list.ts
src/commands/web/get.ts
src/commands/web/list.ts
src/storage/util.ts

this touches upon
https://github.com/nimbella/nimbella-cli/issues/37
https://github.com/nimbella/nimbella-cli/issues/38
https://github.com/nimbella/nimbella-cli/issues/39
https://github.com/nimbella/nimbella-cli/issues/41

Add json and print flags in web, object, and kv [list|get]

---

.github/workflows/build.yml

@joshuaauerbachwatson Here's a WIP for issue #57. 
The build currently [fails here](https://github.com/jthomas/nimbella-cli/runs/1770796354?check_suite_focus=true) because the `npm run lint` command detects the following errors:
```
Run npm run lint
> nimbella-cli@1.11.1 lint /home/runner/work/nimbella-cli/nimbella-cli
> eslint src/**/*.ts deployer/src/**/*.ts --ignore-pattern node_modules
/home/runner/work/nimbella-cli/nimbella-cli/deployer/src/deploy.ts
Error:    91:20   error  Operator '=' must be spaced                     space-infix-ops
Error:    91:24   error  Expected space or tab after '//' in comment     spaced-comment
Error:    94:7    error  'ans' is never reassigned. Use 'const' instead  prefer-const
Error:    99:116  error  Trailing spaces not allowed …
```

Add Github Actions workflow with build tests

---

deployer/src/login.ts

Looks like the right fix for the present.  I remain curious about what the CLI should be able to count upon coming back from login.   I'll merge this (once I have time for a second look) but the question remains.
Thanks.

Get hostname from supplied param

---

deployer/src/api.ts
src/commands/auth/list.ts

links #19
This could be a bigger change, depending on the scope we choose, but this is to get started with the discussions

[auth:list] Change header

---

.eslintignore
awsprovider/src/index.ts
gcsprovider/src/index.ts
package.json
storage/src/index.ts

Auto-fixed all the remaining issues. Closes #59

Update package.json with correct lint checks.

---

src/commands/auth/list.ts

[auth:list] Auth list filtering by hostname.

---

src/generator/project.ts

[project:create] Update project create/update message.

---

src/commands/action/delete.ts
src/commands/auth/logout.ts
src/commands/package/delete.ts
src/commands/rule/delete.ts
src/commands/trigger/delete.ts

Add force flag on delete and logout command

---

deployer/src/util.ts

Remove significant files from exclude list

[project:watch] fix temp file error

---

package.json

Fix high severity vulnerability due to `url-parse`.

Fix vulnerability

---

esbuild.config.js
package-lock.json
package.json
tsconfig.json

This massively speeds up the build & minification by orders of magnitude.
It makes the release process (which runs the build multiple times) faster.

Moving TS compilation to ESBuild.

---

src/commands/auth/logout.ts

use selected host to logout

---

tests/object/objectTesting/test3.txt
tests/object/test.bats
tests/object/test_files/test1.txt
tests/object/test_files/test2.txt

I tested the following commands: object create, get, list, update, url, delete, and clean.

object tests

---

package-lock.json
package.json
tests/object/test.bats

Does what it says in the title.

Fixing system test failure & updating deployer lib.

---

package-lock.json
package.json

Moving deployer dep to v3. This is related to move of NimBaseCommand from deployer lib to CLI.

Moving deployer dep to v3

---

package.json

Revert change to postpack script to allow npm publish

---

package-lock.json
package.json
src/commands/project/get-metadata.ts

This PR contains the initial (and possibly the final, for now) implementation of the new `nim project get-metadata` command.   See issue #187.

Add 'nim project get-metadata' command

---

src/NimBaseCommand.ts

The `NimLogger` abstraction includes a `logJSON` method for simple JSON output but lacks a `logTable` method for tabular output (tabular JSON with separated metadata).   Consequently, tabular output is handled inconsistently in a way that only applies to AIO subtrees.   There should be a consistent output interception methodology across all subtrees.

Expand NimLogger abstraction to cover tables

---

.gitignore
src/commands/auth/github.ts
src/generator/project.ts

My search for "brandable" locations in PR #207 was not quite good enough to find them all.   I probably still don't have them all, but this adds at least a couple more.

Find a few more places where branding is needed.

---

package-lock.json
package.json

Fixes bug in using 'lib' with remote build.
https://github.com/nimbella/nimbella-deployer/releases/tag/v4.0.8
https://github.com/nimbella/nimbella-deployer/releases/tag/v4.0.9

Version 3.0.7 with deployer 4.0.9

---

src/NimBaseCommand.ts

Previously, you could set error verbosity using either the `--verbose` flag or `DEBUG=nim:error` in the environment.  The former is inconvenient for test suites, where you may want error verbosity on globally.  The latter is dangerous when test suites may contain other components that react to `DEBUG` in the environment.  Now you can use `NIM_ERROR_VERBOSITY=<non-empty>` in the environment, which is much less likely to cause problems.

NIM_ERROR_VERBOSITY as alternative to --verbose

---

package-lock.json
package.json

Incorporates deployer 4.0.12, new version 3.0.10

Improved diagnostic when package.json has errors
