CONTRIBUTING.md
commandAuthoringGuide.md

Adding a more general document (`CONTRIBUTING.md`) as per convention.   This references our lint rules and also a more specific document on authoring `nim` subcommands.   As is done elsewhere, the Developer Certificate of Origin is inline and agreeing to it is implicit in submitting any PR.

Add material on contributing to nimbella-cli

---

package.json

The **oclif/plugin-plugins** dependency was pegged at **1.7.9**, it was dependent on **oclif/colors** **0.0.0**, which in turn had an unstated dependency on  "chalk": "^2.4.2".
Adding  **"chalk": "^4.1.0"**, as a host dependency led to this error. 
It's been resolved in updated versions  "@oclif/plugin-plugins": "^1.9.0"

bump oclif/plugin-plugins version

---

deployer/src/deploy.ts

Since the content is entirely opaque post b64 encoding, do not escape any characters when decoding. The JSON serialization and deserialization will handle.

Do not escape encoded wrapped text.

---

deployer/src/NimBaseCommand.ts
deployer/src/api.ts
deployer/src/deploy-struct.ts
deployer/src/deploy.ts
deployer/src/project-reader.ts
deployer/src/util.ts
src/generator/project.ts

This PR adds the `sequence` property to members of the `actions` object in `project.yml`.   The value of this property is an array of action names which are taken to be the members of an openwhisk sequence action.
- the action names 
- may begin with a slash and are assumed to be fully qualified (e.g. may be defined in a different namespace)
- may be package-qualified (with a single slash separator) assumed to be in the target namespace
- may be simple names (assumed to be defined in the default package of the target namespace)
- if an action thus denoted is in the target namespace but is not being deployed in the current deployment
- an information message is issued to that effect but it is not an error
- the deployer does not check specifically for whether such actions have been …

Support sequences

---

deployer/src/util.ts
src/commands/project/deploy.ts

This will remove the hiding logic so that the remote build flag shows up in help and remote builds are tried in the workbench without the need to specify the flag.

Reveal the remote-build capability

---

README.md
deployer/src/deploy-struct.ts
package.json
src/generator/project.ts

Remove unnecessary field from project config template.
Changed ActionSpec type to allow for optional package element.
Updated README.md with more user-friendly instructions for local development based on my experience following instructions.
Also - had to fix Node.js version check command to work on Node.js v15 locally.

Fixing #48

---

deployer/src/NimBaseCommand.ts
deployer/src/github.ts

The ability to deploy from github has so far been bound to `github.com` because it uses `octokit` and, in constructing the `octokit` object, it does not specify a `baseUrl`.   The default `baseUrl` (`https://api.github.com`) is thus assumed.
This change enables enterprise github (and perhaps other api-compatible github servers) to be used in lieu of `github.com`.
1.  When github credentials are established as before, they will continue use the default endpoint `api.github.com`.
2. However, when github credentials are entered manually (by specifying a username and token), the token can optionally specify an alternate endpoint by using the form `<token>@<endpoint>`.
- if the endpoint string does not include `api`, the path `/api/v3` is appended
- if the endpoint string does not include ':', …

Support enterprise github in "deploy from github" feature

---

src/commands/project/serve-web.ts
src/commands/web/serve.ts

If the web folder has `package.json`, it  proxies to the current/given namespace APIs and runs `npm start` otherwise serves static content using 'npx http-server'
links #45
Usage:
`nim web serve`  defaults to the current project's web folder 
`nim web serve /projects/nim/demo-projects/election`
`nim web serve /exp/ncovstats`

Add project:serve-web

---

deployer/package.json
deployer/src/NimBaseCommand.ts
deployer/src/api.ts
deployer/src/finder-builder.ts
deployer/src/index.ts
deployer/src/project-reader.ts
deployer/src/util.ts
src/commands/project/watch.ts

The intention is to have a system-defined ignore pattern list and also allow users to specify `ignore` patterns via `.exclude` file in the project root.
WIP:
the  watcher is working (i.e. ignoring the changes in files matching exclude patterns), but the deployer `doDeploy` is still having the error, will have to work on it 
relates to #46

[project:watch] fix temp file error

---

deployer/nimbella-runtimes.json

Noticed this was missing whilst porting over the tests. Dotnet projects fail to deploy due to missing runtime config.

Adding dotnet runtime to runtimes config

---

.gitignore

I noticed that the repo clone was dirty after running bats tests.

Ignore deployer-generated zip files

---

deployer/src/deploy.ts
tests/sequence/packages/test-sequence/increment.js
tests/sequence/project.yml
tests/sequence/sushi.json
tests/sequence/test.bats

This PR covers a loose end from the original work to add sequence support under PR #34 (merged in December, 2020).   It has been a temporary restriction since then that a sequence may not include, as a component, another sequence which is being deployed at the same time.  The change that is provided here removes that restriction.
The existing `sequence` functional test is enhanced to include some sequences that include other sequences.
Incidentally, the PR also tweaks the sequence test to use a parameter file rather than complexly quoted string parameter value in its older logic.   We have recently found shell quoting fragility problems running the test in different environments.

Sequences may include sequences from same project

---

tests/watch/test.bats
tests/web_cache/test.bats

As we are getting the tests to run on a linux system (and to run automated), the `watch` test does not work there.  There is a failure in the teardown step trying to kill subprocesses.   I also suspect from previous data that this test is a bit non-deterministic (although I usually works on mac) ... it has a somewhat tricky two-process structure.  I am not deleting the test but am setting it to skip itself internally until we have a chance to revise it and make it solid again.
In addition, I have found the `web_cache` test to be fragile.  This is not a Jenkins problem per se, but the test is dependent on white space in headers returned by the `nginx` being tested.   The test currently works on `nimgcp` namespaces but has started failing on GCP test projects with the latest `nginx` image. …

Fixes to bats tests for Jenkins, Linux, etc.

---

.gitignore

Adds entries to `.gitignore` to support NImbella Corp. production builds, which do some tailoring and incorporate some documents (e.g. change log).

Ignore files added during some Nimbella builds

---

tests/web_cache/test.bats

The test for the web cacheing control feature relies on specific header contents that are returned by default when using the Nimbella stack on GCP.   When the stack is run on AWS (EKS), default behavior is different and the test is failing.   This change adjusts for the differences between the two clouds.
An adjustment to how Nimbella declares cacheing behavior for EKS is pending which will make this change effective.   This PR can be merged ahead of that adjustment, since the test on GCP is unaffected and the test is already failing on EKS.

Fix web-cache test when run on AWS/EKS

---

src/commands/project/serve-web.ts

-  disables cache for live reload, bug #110
- removes web suffix to avoid confusing behaviour and unnecessary constraint, bug #111 
- adds port parameter, as you may have a port conflict

serve-web fixes to make it more useful

---

package-lock.json
src/index.ts

Exporting from `nimbella/nimbella-deployer/lib/NimBaseCommand` leads to Module not found error in dependent projects.
Additionally `setHelpHelper` is used by workbench only and it already refers `deployer` as a direct dependency.

stop exporting setHelpHelper function

---

tests/object/test.bats

Small re-factoring to resolve issue here:
https://github.com/nimbella/nimbella-cli/runs/3253344581?check_suite_focus=true
Whilst fixing the issue - I did a little re-factoring based on my experience writing all the other tests to make them more consistent with the codebase. 
- Use $BATS_TEST_DIRNAME instead of $PWD when running tests as this allows you to run the tests from any directory. 
- Use diff to compare objects retrieved via URLs to check they have the same file contents
@saxena52 Can you have a look over my proposed changes and ensure you're happy with them before I merge?

Fixing failing integration test in CI pipeline.

---

package-lock.json
package.json

This PR updates `package.json` and `package-lock.json` with several changes.
1.  Deployer version goes from 3.0.0 to 3.0.1, incorporating fixes in that release.
2. AIO version goes from v2021-07-23-1 to v2021-11-19-1 incorporating fixes in that release.
3. The `commander-cli` dependency is removed.  It is currently broken.  Plans to restore it are unknown at this time.

Remove commander + use latest deployer and aio dependencies

---

src/generator/samples.ts

It was noted by a user of `nim project create` that the formatting of the `golang` example is not consistent with the `gofmt` standard.   This change corrects that error.
Probably the formatting of some other samples needs attention but the rules vary so much by language that I am not taking on the general problem at this time.

Fix golang example formatting

---

package-lock.json
package.json
src/commands/info.ts
src/commands/project/deploy.ts
src/commands/project/get-metadata.ts

This change incorporates version 3.0.6 of the deployer.   In doing so, it fixes a problem with remote build.
Also bumps the patch release to 1.18.3 so that this can be published and incorporated into runtime builds.

Fix runtimes init

---

src/commands/project/get-metadata.ts

The 'project get-metadata' command is intended to provide a comprehensive inspection capability for a project.  As such it doesn't really require any credentials.   However, the command was reading the runtimes table.   To do this, it needs an API host.  It was relying on the current API host recorded in the credentials for this.   When this step is removed, the requirement for the credential store to be initialized is eliminated.
It would be _useful_ (should not be required) for this command to have access to a controller in a running deployment so that it can interrogate information that is not otherwise known (for example, the default versions of various languages for which there are runtimes and the default values of the limits).   That may be added in the future, but, at present it …

Remove reading of runtimes table from 'project get-metadata'

---

package-lock.json
package.json
src/commands/project/get-metadata.ts

A small fix to the result of get-metadata to make it more useful with projects that require symbols in the environment to complete their definition.

Get-metadata to return symbols needed by a project without calling it an error 

---

.gitignore
package-lock.json
package.json
src/commands/project/deploy.ts
src/commands/project/get-metadata.ts
src/commands/project/watch.ts
tests/build-env/build.env
tests/build-env/packages/test-build-env/test/build.sh
tests/build-env/packages/test-build-env/test/index.js
tests/build-env/project.yml
tests/build-env/test.bats
tests/object/test.bats

This adds a flag to `nim project [deploy | watch ]` that permits a property file (identical to that supported by `--env`) to be passed to the build step.   The properties it defines become part of the process environment during the build but have no effect on the runtime environment of the action (unless steps are taken via `project.yml` and `--env` to pass the same values to both).
When this change is in `nim` it will work immediately for local builds.   Before it can work for remote builds, new `nim` must be incorporated into the runtimes.  This is not in plan for `apigcp` but will be in a future deployment.

Add --build-env flag to project deploy (and watch)

---

.gitignore
package-lock.json
package.json
tests/test_setup.bash
tests/toomany/test.bats

The new test attempts to deploy a package with 500 actions in it.   This is likely to fail until after the deployer PR nimbella/nimbella-deployer#46 is merged and a new deployer release is incorporated.

Add a test for deploying a very large number of actions

---

src/NimBaseCommand.ts

The `CaptureLogger` is the object returned by `runNimCommand` when `nim` commands are invoked via the library interface.   
Previously, if the output was tabular (e.g. `nim action list`) the table was captured as an object array which enabled creative display but made it hard to reconstruct the "normal" textual format.
The new behavior is to return the object array as before in the `table` member but to include also `tableColumns` and `tableOptions` from the captured call to `cli-ux table`.   This allows `cli-ux` to be used on the returned `CaptureLogger` to reconstruct the usual textual form.   Backward compatibility is achieved by only adding fields, which can be ignored by callers that do not expect them.

Improvement to CaptureLogger

---

package.json

The advantages of having an `update` command are lost under the present circumstances (the original update site on `nimbella.io` is no longer hosting new versions).
Planned future packaging of `nim` does not require it to have an update site.
Yet, the presence of an `update` command, an update plugin, and an update site reference in `package.json` conspire to allow users to shoot themselves in the foot by updating to what is actually an older version and making that older version hard to find and delete when using other packaging techniques.
This PR removes the update command and plugin and the update site reference.   Despite this "loss of functionality" I am not going to regard this as a breaking change for versioning purposes

Remove update site pointer from installed 'nim'

---

package-lock.json
package.json
src/commands/project/get-metadata.ts

It is now possible to get back a largely valid structure with variables missing.  So, the error handling in `project get-metadata` should take that into account and display all the information it has.
For this change to be effective, it requires a change in the deployer.  So, the merge of this PR should wait on the release of a new deployer.   The dependency update can then be incorporated in this PR prior to merge.

New handling for unresolved vars in get-metadata

---

src/NimBaseCommand.ts
src/commands/auth/current.ts
src/commands/auth/export.ts
src/commands/key-value/list.ts
src/commands/object/list.ts
src/commands/project/get-metadata.ts
src/commands/web/list.ts

The CLI is often used in scripts or in a dependent fashion (through the library interface) in which case a more structured form of output is desirable.
Some commands have a `--json` flag but one has to know which.   With this change, there is a global `--json` flag so that flag will be accepted on every command.
Not all commands will respond to this flag by actually issuing JSON, so think of it as advisory.    But, part of this PR is to make sure that all commands that do honor a `--json` flag are using the global one and are using the recommended method of `NimLogger (`logJSON`).   There will be follow-on work to make more and more commands conform to the implied mandate of the flag.

Establish global --json flag, unify some uses

---

package-lock.json
package.json
src/NimBaseCommand.ts
src/commands/auth/current.ts
src/commands/auth/env.ts
src/commands/auth/github.ts
src/commands/auth/list.ts
src/commands/auth/login.ts
src/commands/auth/logout.ts
src/commands/auth/refresh.ts
src/commands/auth/switch.ts
src/commands/project/deploy.ts
src/commands/project/get-metadata.ts
src/commands/project/watch.ts
src/generator/project.ts
tsconfig.json

With this PR, the new `--json` flag is respected by all `nim auth ...` commands and many `nim project ...` commands.   The `project watch` and `project serve-web` commands, which, by design produce continuous output in a separate console window, are not changed for now.

Support --json flag in 'nim auth' and 'nim project' topics

---

src/NimBaseCommand.ts
src/commands/auth/export.ts
src/commands/auth/list.ts
src/commands/auth/login.ts
src/commands/auth/logout.ts
src/commands/auth/refresh.ts
src/commands/auth/switch.ts
src/commands/doc.ts
src/commands/info.ts
src/commands/object/create.ts
src/commands/object/update.ts
src/commands/project/create.ts
src/commands/project/deploy.ts
src/commands/project/get-metadata.ts
src/commands/project/update.ts
src/commands/project/watch.ts
src/commands/web/create.ts
src/commands/web/update.ts
src/commands/workbench/login.ts
src/commands/workbench/run.ts
src/index.ts
src/workbench.ts

The brand name "Nimbella", references to the command name 'nim', and assumptions that the host is a subdomain of 'nimbella.io', were scattered throughout the code.   This change introduces a mutable `branding` structure in `NimBaseCommand` that is then consulted in all of these places.   The default behavior remains the same but an invoker using the library interfaces can now change this structure to "re-brand" the CLI.

Introduce "branding" abstraction for altering output details

---

src/NimBaseCommand.ts
src/commands/project/watch.ts
src/index.ts

This PR includes two fixes.
1.  A new library function `runNimCommandNoCapture` was added.   It is like `runNimCommand` but does not capture the output, which continues to go to `stdout`.   The intended use case is when invoking something like `project watch` or `project serve-web` that will run indefinitely in a separate window.
2. In using the above with `project watch` I discovered a bug in `project watch` (probably a bug in `chokidar`) .   If you are watching an area in which there might be  symlinks, the watcher can get fired repeatedly for a symlink that doesn't actually change.   It seems like symlinks always appear to be freshly added.  Since Nimbella projects do not depend on symlinks much and we actively discourage using them, I decided to fix this by ignoring symlink adds. …

(1) runNimCommandNoCapture added. (2) fix to 'project watch' when symlinks

---

package-lock.json
package.json
tests/remote-build-go/test.bats
tests/remote-build-java/test.bats
tests/remote-build-php/test.bats
tests/remote-build-python/test.bats
tests/remote-build-swift/test.bats

Depending on the API host, the remote build initiation messages may add an activation id at the end.   This capability comes with deployer 3.1.12.  Remote build tests must adjust.

Initiation message for remote build now includes the activation id

---

package-lock.json
package.json

1. Correct error message when --remote-build combined with missing
symbols in project.yml.
2. Propagate a global environment correctly on remote build.
3. Show error rather than ignore when parameters/environment adhere to
the default package (this package is not real and the result will not
be as expected).

Upgrade to deployer 3.1.4, fixing several bugs.

---

tests/remote-build-go/packages/test-remote-build-go/dependencies/go.mod
tests/remote-build-go/packages/test-remote-build-go/dependencies/main.go
tests/remote-build-go/project.yml
tests/remote-build-go/test.bats

As per title. This is an important flow to run in the context of limiting where users can or cannot write inside of the container.

Add a test to remote-build-go that exercises dep downloading

---

tests/remote-build-nodejs/packages/test-remote-build-nodejs/default/main.js
tests/remote-build-nodejs/packages/test-remote-build-nodejs/default/package.json
tests/remote-build-nodejs/test.bats

A gap in our testing currently.

Add a test for remote builds of Node.js actions

---

package-lock.json
package.json
src/commands/info.ts
src/commands/project/create.ts
src/generator/project.ts

The main purpose of this PR is eliminate a gotcha when creating a project.   The `nim project create` command was using a fixed list of languages and just assuming that all those languages were supported in the backend by installed runtimes.   This implied invariant happened to be true of the `nimgcp` deployment at the time.
In considering deployments with a smaller (or different) complement of runtimes, this can lead to a developer creating a project which cannot be deployed.    Fixes issue #218.
In adding the check several bugs were discovered that need to be fixed.
1.  In the deployer, the `isValidRuntime` utility was incorrect.   That is fixed in release `3.1.21` of the deployer.
2. In the CLI, the `nim info --runtimes` command was racy (it becomes part of this fix because the …

Project create should check that a runtime exists for a project before creating it

---

tests/multi_substitute/packages/test-multi-substitute/hello.js
tests/multi_substitute/test.bats

As per title. The current test assumes that `action get` returns the parameters in a specific order and with the values in clear text. That won't work in a system with encrypted parameters, so change the test to invoke the action and make it return the values instead.

Make substitution test work regardless of encryption

---

src/NimBaseCommand.ts

Previously, errors that were not thrown (e.g with 'displayError') would come back in 'captured' and there would be no distinction between them and normal output.   This can undermine some library uses of the CLI where, in the presence of a non-zero exit, it is otherwise unclear what is an error and what is normal.

When capturing, all errors should be distinguished

---

package-lock.json
package.json

This change incorporates deployer version v4.0.6 and changes some dev dependencies to match the versions used in the deployer.   The deployer change, in turn, eliminates reported vulnerabilities, eliminates testing on node versions < 14.0, and updates esbuild and jest dependencies, which had grown pretty stale.

Version 3.0.5 - fixes vulnerabilities and aligns dev dependencies with the deployer

---

package-lock.json
package.json

This PR stages release v3.0.6, which Incorporates deployer 4.0.7.   That, in turn, fixes a bug when a remote build initiated from windows has a `build.sh`.  There was no way previously to mark this as executable and so the build generally failed with a permissions error and exit code 126.

Release v3.0.6 with bug fix for remote build initiated from windows

---

src/NimBaseCommand.ts
src/commands/project/deploy.ts

This change consists of a small adjustment to the `branding` structure in `NimBaseCommand`.   It now abstracts the header that is shown immediately before the list of successfully deployed projects when using `project deploy`.   It also avoids using the term `project` in the initial header.
The version was incremented to 3.0.7 prior to this change but that release has not been published.   It will be published including this change.

Improve branding around output of deploy command

---

package-lock.json
package.json

Incorporates deployer 4.1.0 and sets CLI version 3.1.0.
This changes allows environment variables or properties in an environment file to have multi-line (newline-separated) values.  At substitution time, these are escaped by default so as to go through the YAML parser as strings.   The escaping can be suppressed using the special syntax `${|SYMBOL}`.   See https://github.com/nimbella/nimbella-deployer/pull/86 for more details.

Support multi-line string values in symbolic substitution

---

package-lock.json
package.json

Because the Nimbella deployer had locked down version 7.0.0 of the `dotenv` parser, its environment files don't support the latest multi-line syntax recommendations of `dotenv`.   This PR incorporates deployer 4.1.1 and declares CLI 3.1.1 to pick up the change to fix this.   The latest `dotenv` should now be used.

Support multi-line syntax in environment files

---

src/generator/project.ts

When generating a new project using `nim project create` the `.gitignore` file that is generated now includes `.deployed` as well as `.nimbella`.   This is the new name that the deployer will be using for the deployer-generated status directory of a project.   I chose not to remove `.nimbella` altogether since a developer with a mixture of old and new projects may end up copying or cutting and pasting `.gitignore` files.

Use .deployed, not .nimbella, for status directory

---

package-lock.json
package.json
src/commands/project/get-metadata.ts
src/generator/project.ts

This change declares a new major release of the CLI (4.0.0) incorporating a new release of the deployer (4.2.0).   There are three changes.
1.  The status directory generated by the deployer in the base of a deployed project is now called `.deployed` rather than `.nimbella`.    This change is backward compatible _for the most part_ in that both `.nimbella` and `.deployed` continue to be ignored by the deployer during project reading.   However, only `.deployed` will be generated and only `deployed` will be re-read during incremental deploys, so there can be a one-time hiccup in incremental deployment where the entire project is deployed.
2. The parsing of `project.yml` now accepts both `functions` and `actions` where only `actions` was accepted before.   This is also a …

Use 'functions' not 'actions' in project.yml and use .deployed instead of .nimbella

---

package-lock.json
package.json

Incorporates deployer 4.2.1 with the fix and declares version 4.0.1
Previous to this fix, the combination of `--verbose-build`, `--remote-build` and an actual build failure would incorrectly cause the build transcript to be omitted.

Fix remote verbose build behavior

---

package-lock.json
package.json

There is a direct dependency on `aio-lib-runtime` in `invoke.ts` but this dependency is not declared in `package.json`.   We have generally gotten away with this but, depending on the version of `npm` that is used, it can also cause a failure.   There is always an indirect dependency via `aio-cli-plugin-runtime` so it depends on how `npm` decides to hoist things.
This simply adds the missing direct dependency.

The aio-lib-runtime dependency should be explicit

---

package-lock.json
package.json
src/main.ts

When using Nimbella CLI or Nimbella Deployer via library interfaces, there is an opportunity to set the user agent string on the `initializeAPI` call.   But, when invoking the CLI at a terminal, the `initializeAPI` call has so far used a hard-coded constant so there is no opportunity to tailor the user agent string by context.  
This change introduces the environment variable `NIM_USER_AGENT` which can be used to set an alternative user agent string.   If the environment variable is unset (or set to the empty string), then the hard-coded constant is used as before.
The change is motivated by the fact that `nim` is often used in a context where it is embedded in something else and the generic user agent string is not informative enough.

Make the user agent string tailorable via the process environment

---

package-lock.json
package.json
src/commands/action/delete.ts

1.  Adopt deployer 4.3.2, which has support for "triggers" in `project.yml` and links triggers to functions via annotations.
2. Use the deployer's `deleteAction` function instead of `aio` when deleting an action.  This allows associated cleanup of the triggers.
The "triggers" being referred to here are not OpenWhisk triggers but rather ones being maintained in another service.

Support for triggers

---

package-lock.json
package.json
src/generator/project.ts

This change provides a more realistic way to support typescript in the `nodejs` runtime, rather than assuming there is a 
specialized typescript runtime.
When you specify `nim project create ... --language typescript` the runtime kind is set to `nodejs` but the project is set up with additional material (`package.json`, `tsconfig.json`, `.include`, and `src` and `lib` folders) so that a simple action written in typescript will run.   It should be easy  to generalize this by adding source files, or adding dependencies, modifying generated `.include` accordingly.
Generalizing to multiple actions with shared material should also be easy but will need more validation and may result in some further changes.   The basic structure can be relocated to `lib` and then the multiple source files are …

Project create now supports typescript in nodejs

---

package-lock.json
package.json
src/commands/project/deploy.ts

Since version 4.2.0 `nim` had offered support for triggers (via the deployer).   These are not OpenWhisk triggers but triggers implemented by DIgitalOcean external to the OpenWhisk cluster.
This change  moves trigger support closer to the point where it will be ready to be released to the public.   The change does two things
1.  It changes the logic in `nim` proper so that trigger deployment successes and failures are reported independently of action (function) successes and failures.   Although triggers are tied to functions, their deployment is separable and can fail even when the function deployment succeeds. 
2. It brings in the latest deployer version in which contact to the backend goes via an API that is closer to what will eventually be supported.

Report trigger deployment success/failure + use updated API to the backend

---

package-lock.json
package.json
src/commands/action/delete.ts

Incorporates deployer 4.3.9, declares version 4.2.7.
See https://github.com/nimbella/nimbella-deployer/releases/tag/v4.3.9.
Also changes `action delete` to respond more appropriately to the new-style error returns from the deployer's `deleteAction` function.

Ensure more orderly deletion of triggers

---

package-lock.json
package.json

This change incorporates a fix to the deployer in version 4.3.10.  When the attempt is made to list triggers during a "wipe" operation (namespace or package) or when deleting a function, the attempt is allowed to fail silently.  Some users may not be authorized to the triggers API and so will not have any triggers.   If the API fails, the empty list is returned.

Fail silently when listing triggers if not authorized
